plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
def cachedKotlinStdlib = file('C:/Users/Microsoft/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.10/30de6faa127a4a012db8e71bf1b9c0a99b1402b2')

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        if (cachedKotlinStdlib.exists()) {
            flatDir { dirs cachedKotlinStdlib }
        }
    }
}

rootProject.name = "VoiceBench"
include(":app")
